Header:
    version: 135
StyleSheets:
-   selectors:
    - ".1st_april.equipment_item.largeRepairkit ? #icon"
    - ".1st_april.equipment_item.largeRepairkit #icon"
    properties:
        bg-sprite: "~res:/Gfx/UI/InventoryIcons/Big/Event/largeRepairkit_apr.txt"
-   selectors:
    - ".equipment_item.forsage ? #icon"
    - ".equipment_item.forsage #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_forsage_m"
-   selectors:
    - ".equipment_item.buff ? #icon"
    - ".equipment_item.buff #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_buff_1_m"
-   selectors:
    - ".equipment_item.dash ? #icon"
    - ".equipment_item.dash #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_dash_m"
-   selectors:
    - ".equipment_item.hunters ? #icon"
    - ".equipment_item.hunters #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_hunters_m"
-   selectors:
    - ".equipment_item.moonwalk ? #icon"
    - ".equipment_item.moonwalk #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_moonwalk_m"
-   selectors:
    - ".equipment_item.ram ? #icon"
    - ".equipment_item.ram #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_ram_m"
-   selectors:
    - ".equipment_item.shield ? #icon"
    - ".equipment_item.shield #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_shield_m"
-   selectors:
    - ".equipment_item.stealth ? #icon"
    - ".equipment_item.stealth #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_stealth_m"
-   selectors:
    - ".equipment_item.vampire ? #icon"
    - ".equipment_item.vampire #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_vampire-heal_m"
-   selectors:
    - ".equipment_item.victim ? #icon"
    - ".equipment_item.victim #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2020_Mad-games/big/consumable_victim_m"
-   selectors:
    - ".equipment_item.comeback-kit ? #icon"
    - ".equipment_item.comeback-kit #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_come-back-kit_m"
        bg-frame: 0
-   selectors:
    - ".equipment_item.engine-boost ? #icon"
    - ".equipment_item.engine-boost #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_engine-boost_1_m"
-   selectors:
    - ".equipment_item.engine-boost_2 ? #icon"
    - ".equipment_item.engine-boost_2 #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_engine-boost_2_m"
-   selectors:
    - ".equipment_item.damage-boost ? #icon"
    - ".equipment_item.damage-boost #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_damage-boost_1_m"
-   selectors:
    - ".equipment_item.damage-boost_2 ? #icon"
    - ".equipment_item.damage-boost_2 #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_damage-boost_2_m"
-   selectors:
    - ".equipment_item.reload-boost ? #icon"
    - ".equipment_item.reload-boost #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_reload-boost_1_m"
-   selectors:
    - ".equipment_item.reload-boost_2 ? #icon"
    - ".equipment_item.reload-boost_2 #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_reload-boost_2_m"
-   selectors:
    - ".equipment_item.duplet ? #icon"
    - ".equipment_item.duplet #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_duplet_m"
-   selectors:
    - ".equipment_item.ghost ? #icon"
    - ".equipment_item.ghost #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_ghost_m"
-   selectors:
    - ".equipment_item.ramming ? #icon"
    - ".equipment_item.ramming #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_ramming_1_m"
-   selectors:
    - ".equipment_item.ramming_2 ? #icon"
    - ".equipment_item.ramming_2 #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_ramming_2_m"
-   selectors:
    - ".equipment_item.splash ? #icon"
    - ".equipment_item.splash #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_splash_m"
-   selectors:
    - ".equipment_item.lightning ? #icon"
    - ".equipment_item.lightning #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_lightning_1_m"
-   selectors:
    - ".equipment_item.lightning_2 ? #icon"
    - ".equipment_item.lightning_2 #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_lightning_2_m"
-   selectors:
    - ".equipment_item.enemy-reload-time ? #icon"
    - ".equipment_item.enemy-reload-time #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/provisions/2019_Halloween/provision_enemy-reload-time_m"
        bg-frame: 1
-   selectors:
    - ".equipment_item.curse ? #icon"
    - ".equipment_item.curse #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_curse_m"
-   selectors:
    - ".equipment_item.tornado ? #icon"
    - ".equipment_item.tornado #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_vortex_m"
-   selectors:
    - ".equipment_item.return-in-time ? #icon"
    - ".equipment_item.return-in-time #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_return-in-time_m"
-   selectors:
    - ".equipment_item.halloween_hunters_mark ? #icon"
    - ".equipment_item.halloween_hunters_mark #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_hunters-mark_m"
-   selectors:
    - ".equipment_item.halloween_moonwalk ? #icon"
    - ".equipment_item.halloween_moonwalk #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_moonwalk_m"
-   selectors:
    - ".equipment_item.pretend-dead ? #icon"
    - ".equipment_item.pretend-dead #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2019_Halloween/consumable_pretend-dead_m"
-   selectors:
    - ".equipment_item.jump ? #icon"
    - ".equipment_item.jump #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_Lunar/big/consumable_jump_m"
-   selectors:
    - ".equipment_item.gravity-burst ? #icon"
    - ".equipment_item.gravity-burst #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_scatter_m"
-   selectors:
    - ".equipment_item.healing-aura ? #icon"
    - ".equipment_item.healing-aura #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_aura-of-healing_m"
-   selectors:
    - ".equipment_item.railgun-charger ? #icon"
    - ".equipment_item.railgun-charger #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_enhanced-shot_m"
-   selectors:
    - ".equipment_item.shield-giver-ability ? #icon"
    - ".equipment_item.shield-giver-ability #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_energy-shield_m"
-   selectors:
    - ".equipment_item.permanent-damage-shield ? #icon"
    - ".equipment_item.permanent-damage-shield #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_damage-resistance_m"
-   selectors:
    - ".equipment_item.kamikaze-ability ? #icon"
    - ".equipment_item.kamikaze-ability #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_bang-boom_m"
-   selectors:
    - ".equipment_item.poisoned-shell ? #icon"
    - ".equipment_item.poisoned-shell #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_poisoned-shells_m"
-   selectors:
    - ".equipment_item.gravity-shot ? #icon"
    - ".equipment_item.gravity-shot #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_gravity-shot_m"
-   selectors:
    - ".equipment_item.gravity-shot ? #icon"
    - ".equipment_item.gravity-shot #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_gravity-shot_m"
-   selectors:
    - ".equipment_item.healingShot ? #icon"
    - ".equipment_item.healingShot #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_shot-heailing_m"
-   selectors:
    - ".equipment_item.killerPassive ? #icon"
    - ".equipment_item.killerPassive #icon"
    - ".equipment_item.kamikazePassive ? #icon"
    - ".equipment_item.kamikazePassive #icon"
    - ".equipment_item.big-boss ? #icon"
    - ".equipment_item.big-boss #icon"
    properties:
        bg-sprite: "~res:/Gfx/Shared/tank-supply/consumables/2021_BossMode/big/consumable_tanks-ttx-up_m"
