Header:
    version: "100"
ImportedPackages:
- "~res:/UI/Screens3/Lobby/Common/CheckMark.yaml"
- "~res:/UI/Screens3/Lobby/Common/Selection.yaml"
Prototypes:
-   class: "UIControl"
    name: "Skill"
    size: [64.000000, 64.000000]
    exclusiveInput: true
    components:
        UIAnchorSafeAreaComponent:
            leftSafeInset: "INSET"
        UIAttachLayoutMasterComponent: {}
        UISwitchBarElementComponent: {}
        UIDataParamsComponent:
            params:
            - ["vector<string>", "activeSkills", "[ ]", "[ \"lucky_shot\"; ]"]
            - ["Skill", "skill", "null", "{ }"]
            - ["bool", "isSelected", "false", "true"]
            - ["bool", "isTankClassSelected", "false", "false"]
            - ["eTutorialHighlights", "currentHighlightControl", "eTutorialHighlights.kUnknown", "eTutorialHighlights.kUnknown"]
        UIDataLocalsComponent:
            locals:
            - ["int", "progress", "when not isNull(skill) -> int(skill.progress * 100), 0"]
            - ["bool", "checkMarkVisible", "when not isNull(skill) -> skill.level == skill.maxLevel, false"]
            - ["bool", "levelVisible", "when not isNull(skill) -> skill.level > 0, false"]
            - ["bool", "progressVisible", "when not isNull(skill) -> activeSkills.Contains(skill.skillName) and skill.level < skill.maxLevel, false"]
            - ["bool", "isCurrentSkillTutorial", "isTankClassSelected and currentHighlightControl == eTutorialHighlights.kCurrentSkillTrain and isSelected"]
            - ["bool", "isOtherSkillsTutorial", "isTankClassSelected and currentHighlightControl == eTutorialHighlights.kLastSkill and not isSelected"]
            - ["string", "attachId", "when isCurrentSkillTutorial -> \"CURRENT_SKILL_TRAIN\", \"\""]
        Sound: {}
        UIShadowHoleComponent:
            leftOffset: 8.000000
            rightOffset: 8.000000
            topOffset: 8.000000
            bottomOffset: 16.000000
        StyleSheet:
            styles: "~res:/UI/Screens3/SafeArea.style.yaml;~res:/UI/Screens3/ButtonSound.style.yaml;~res:/UI/Screens3/Color.style.yaml;~res:/UI/Screens3/Lobby/Inventory/Crew/SkillImage.style.yaml;~res:/UI/Screens3/Common/Touch.style.yaml"
    bindings:
    - ["input", "not isSelected"]
    - ["classes", "\"button-choose-sound crew-slot crew_skills \" + skill.skillName"]
    - ["UIAttachLayoutMasterComponent.attachId", "attachId"]
    - ["UISwitchBarElementComponent.id", "skill.skillName"]
    - ["UIShadowHoleComponent.isEnabled", "isCurrentSkillTutorial or isOtherSkillsTutorial"]
    children:
    -   class: "UIControl"
        name: "Content"
        position: [32.000000, 32.000000]
        size: [32.000000, 32.000000]
        pivot: [0.500000, 0.500000]
        input: false
        classes: "content-area"
        components:
            Anchor:
                hCenterAnchorEnabled: true
                vCenterAnchorEnabled: true
            SizePolicy:
                horizontalPolicy: "PercentOfParent"
                verticalPolicy: "PercentOfParent"
        children:
        -   class: "UIControl"
            name: "Highlight"
            position: [-18.000000, -18.000000]
            size: [100.000000, 100.000000]
            input: false
            components:
                Anchor:
                    hCenterAnchorEnabled: true
                    vCenterAnchorEnabled: true
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfParent"
            bindings:
            - ["visible", "skill.highlighted"]
        -   class: "UIControl"
            name: "Progress"
            size: [32.000000, 32.000000]
            input: false
            components:
                Anchor:
                    bottomAnchorEnabled: true
                    bottomAnchor: -12.000000
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "FixedSize"
                    verticalValue: 4.000000
            bindings:
            - ["visible", "progressVisible"]
            children:
            -   class: "UIControl"
                name: "ProgressBar"
                input: false
                components:
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfParent"
                    UIChildComponent0:
                        prototypePath: "~res:/UI/Screens3/Lobby/Common/ProgressBar.yaml"
                        args:
                            "value": "progress"
        -   class: "UIControl"
            name: "Background"
            size: [32.000000, 32.000000]
            input: false
            classes: "black-25-bg"
            components:
                Background:
                    drawType: "DRAW_FILL"
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfParent"
        -   prototype: "Selection/Selection"
            name: "Selection"
            components:
                UIDataParamsComponent:
                    args:
                        "isVisible": "isSelected"
        -   class: "UIControl"
            name: "Icon"
            size: [98.000000, 98.000000]
            input: false
            classes: "skill-img"
            components:
                Background:
                    drawType: "DRAW_SCALE_TO_RECT"
                    colorInherit: "COLOR_MULTIPLY_ALPHA_ONLY"
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfParent"
        -   prototype: "CheckMark/CheckMark"
            name: "CheckMark"
            components:
                Anchor:
                    rightAnchorEnabled: true
                    rightAnchor: -8.000000
                    bottomAnchorEnabled: true
                    bottomAnchor: -8.000000
                UIDataParamsComponent:
                    args:
                        "isVisible": "checkMarkVisible"
        -   class: "UIControl"
            name: "Level"
            size: [32.000000, 32.000000]
            input: false
            components:
                Anchor:
                    leftAnchorEnabled: true
                    leftAnchor: -8.000000
                    topAnchorEnabled: true
                    topAnchor: -8.000000
                SizePolicy:
                    horizontalPolicy: "FixedSize"
                    horizontalValue: 24.000000
                    verticalPolicy: "FixedSize"
                    verticalValue: 24.000000
            bindings:
            - ["visible", "levelVisible"]
            children:
            -   class: "UIControl"
                name: "Bg"
                size: [32.000000, 32.000000]
                input: false
                classes: "gray-cape-cod-bg"
                components:
                    Background:
                        drawType: "DRAW_STRETCH_BOTH"
                        sprite: "~res:/Gfx/Lobby/backgrounds/bg_r2"
                        leftRightStretchCap: 2.000000
                        topBottomStretchCap: 2.000000
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfParent"
                    StyleSheet:
                        styles: "~res:/UI/Screens3/Color.style.yaml"
            -   class: "UIControl"
                name: "Value"
                input: false
                classes: "bold t-caption white-wild-sand-text not-localize"
                components:
                    UITextComponent:
                        fitting: "FITTING_POINTS"
                        align: ["RIGHT", "VCENTER"]
                        useRtlAlign: "USE_BY_CONTENT"
                    Anchor:
                        hCenterAnchorEnabled: true
                        vCenterAnchorEnabled: true
                    SizePolicy:
                        horizontalPolicy: "PercentOfContent"
                        verticalPolicy: "PercentOfContent"
                    StyleSheet:
                        styles: "~res:/UI/Screens3/Font.style.yaml"
                bindings:
                - ["UITextComponent.text", "skill.level"]
