Header:
    version: "79"
ImportedPackages:
- "~res:/UI/Screens3/Lobby/Common/Resource/Currencies.yaml"
- "~res:/UI/Screens3/Lobby/Common/RichText.yaml"
Prototypes:
-   class: "UIControl"
    name: "Info"
    size: [500.000000, 144.000000]
    input: false
    components:
        LinearLayout:
            padding: "16"
        SizePolicy:
            horizontalPolicy: "PercentOfParent"
            horizontalValue: 95.000000
            horizontalMax: 640.000000
            verticalPolicy: "PercentOfLastChild"
        UIDataParamsComponent:
            params:
            - ["eCamouflageKind", "slot", "eCamouflageKind.WINTER", "eCamouflageKind.WINTER"]
            - ["eCamoInShopState", "state", "eCamoInShopState.INSTALL", "eCamoInShopState.UNLOCK_CLAN_LEVEL"]
            - ["CamouflageLock", "camouflageLock", "null", "{ clanLevel = 3; }"]
            - ["Price", "supplyPrice", "null", "{ }"]
            - ["string", "description", "\"\"", "\"Bla bla bla\""]
            - ["bool", "visible", "true", "true"]
            - ["string", "name", "\"\"", "\"Camo\""]
        UIDataLocalsComponent:
            locals:
            - ["string", "formattedTags", "when state == eCamoInShopState.UNLOCK_CLAN and not (camouflageLock.clanTags.Size() == 1) -> FormatClanTags(camouflageLock.clanTags), \"\""]
            - ["string", "lockDescription", "when state == eCamoInShopState.UNLOCK_BUNDLE and slot == eCamouflageKind.CUSTOM_SET -> \"#customSets:Shop/GetBundle\", state == eCamoInShopState.UNLOCK_BUNDLE and not (slot == eCamouflageKind.CUSTOM_SET) -> \"#camouflages:Shop/GetBundle\", state == eCamoInShopState.UNLOCK_PREMIUM and slot == eCamouflageKind.CUSTOM_SET -> \"#customSets:Shop/GetPremium\", state == eCamoInShopState.UNLOCK_PREMIUM and not (slot == eCamouflageKind.CUSTOM_SET) -> \"#camouflages:Shop/GetPremium\", state == eCamoInShopState.UNLOCK_QUEST and slot == eCamouflageKind.CUSTOM_SET -> \"#customSets:Shop/GetEvent\", state == eCamoInShopState.UNLOCK_QUEST and not (slot == eCamouflageKind.CUSTOM_SET) -> \"#camouflages:Shop/GetEvent\", state == eCamoInShopState.UNLOCK_STORY and slot == eCamouflageKind.CUSTOM_SET -> \"#customSets:Shop/GoToEvent\", state == eCamoInShopState.UNLOCK_STORY and not (slot == eCamouflageKind.CUSTOM_SET) -> \"#camouflages:Shop/GoToEvent\", state == eCamoInShopState.UNLOCK_CLAN_LEVEL and slot == eCamouflageKind.CUSTOM_SET -> localize(\"#customSets:Shop/GetClanSupply\", { level = camouflageLock.clanLevel; }), state == eCamoInShopState.UNLOCK_CLAN_LEVEL and not (slot == eCamouflageKind.CUSTOM_SET) -> localize(\"#camouflages:Shop/GetClanSupply\", { level = roman(camouflageLock.clanLevel); }), state == eCamoInShopState.UNLOCK_CLAN and slot == eCamouflageKind.CUSTOM_SET and camouflageLock.clanTags.Size() == 1 -> \"#customSets:Shop/GoToClan\", state == eCamoInShopState.UNLOCK_CLAN and not (slot == eCamouflageKind.CUSTOM_SET) and camouflageLock.clanTags.Size() == 1 -> \"#camouflages:Shop/GoToClan\", state == eCamoInShopState.UNLOCK_CLAN and not empty(formattedTags) and slot == eCamouflageKind.CUSTOM_SET -> localize(\"#customSets:Shop/GoToOneOfClans\", { listClanTag = formattedTags; }), state == eCamoInShopState.UNLOCK_CLAN and not empty(formattedTags) and not (slot == eCamouflageKind.CUSTOM_SET) -> localize(\"#camouflages:Shop/GoToOneOfClans\", { listClanTag = formattedTags; }), \"\""]
    bindings:
    - ["visible", "visible"]
    children:
    -   class: "UIControl"
        name: "Background"
        input: false
        classes: "grey-shark-80-bg"
        components:
            Background:
                drawType: "DRAW_STRETCH_BOTH"
                sprite: "~res:/Gfx/Lobby/backgrounds/bg_r8"
                leftRightStretchCap: 8.000000
                topBottomStretchCap: 8.000000
            IgnoreLayout: {}
            SizePolicy:
                horizontalPolicy: "PercentOfParent"
                verticalPolicy: "PercentOfParent"
            StyleSheet:
                styles: "~res:/UI/Screens3/Color.style.yaml"
    -   class: "UIControl"
        name: "Content"
        input: false
        components:
            LinearLayout:
                spacing: 16.000000
            SizePolicy:
                horizontalPolicy: "PercentOfParent"
                verticalPolicy: "PercentOfMaxChild"
        children:
        -   class: "UIControl"
            name: "LeftPart"
            input: false
            components:
                LinearLayout:
                    orientation: "TopDown"
                    padding: "16"
                    spacing: 4.000000
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    horizontalValue: 300.000000
                    verticalPolicy: "PercentOfChildrenSum"
            children:
            -   class: "UIControl"
                name: "Title"
                input: false
                classes: "t-subtitle bold color=white-wild-sand-text"
                components:
                    UITextComponent:
                        align: ["LEFT", "VCENTER"]
                        useRtlAlign: "USE_BY_SYSTEM"
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfContent"
                    StyleSheet:
                        styles: "~res:/UI/Screens3/Font.style.yaml;~res:/UI/Screens3/Color.style.yaml"
                bindings:
                - ["UITextComponent.text", "localize(name)"]
            -   prototype: "RichText/RichText"
                name: "Description"
                components:
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                    UIDataParamsComponent:
                        args:
                            "baseFontSize": "\"t-body\""
                            "baseFontStyle": "\"regular\""
                            "baseFontColor": "\"white-wild-sand-50-text\""
                            "key": "localize(description)"
                            "resource1Model": "null"
                            "resource2Model": "null"
                            "resource3Model": "null"
                            "resource4Model": "null"
            -   prototype: "RichText/RichText"
                name: "LockInfo"
                components:
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                    UIDataParamsComponent:
                        args:
                            "baseFontSize": "\"t-body\""
                            "baseFontStyle": "\"regular\""
                            "baseFontColor": "\"white-wild-sand-50-text\""
                            "key": "localize(lockDescription)"
                            "linkKey": "\"\""
                            "resource1Model": "null"
                            "resource2Model": "null"
                            "resource3Model": "null"
                            "resource4Model": "null"
                            "customKeyProperty": "\"\""
        -   class: "UIControl"
            name: "Separator"
            input: false
            classes: "white-wild-sand-25-bg"
            components:
                Background: {}
                Anchor:
                    topAnchorEnabled: true
                    topAnchor: 16.000000
                    bottomAnchorEnabled: true
                    bottomAnchor: 16.000000
                SizePolicy:
                    horizontalPolicy: "FixedSize"
                    horizontalValue: 1.000000
                    verticalPolicy: "PercentOfParent"
                StyleSheet:
                    styles: "~res:/UI/Screens3/Color.style.yaml"
        -   class: "UIControl"
            name: "RightPart"
            input: false
            components:
                LinearLayout:
                    orientation: "TopDown"
                    padding: "16"
                SizePolicy:
                    horizontalPolicy: "PercentOfMaxChild"
                    verticalPolicy: "PercentOfMaxChild"
            children:
            -   class: "UIControl"
                name: "ContentArea"
                components:
                    LinearLayout:
                        spacing: 16.000000
                    SizePolicy:
                        horizontalPolicy: "PercentOfChildrenSum"
                        horizontalMin: 127.000000
                        verticalPolicy: "PercentOfMaxChild"
                children:
                -   class: "UIControl"
                    name: "CostWrapper"
                    components:
                        LinearLayout:
                            orientation: "TopDown"
                        SizePolicy:
                            horizontalPolicy: "PercentOfMaxChild"
                            verticalPolicy: "PercentOfChildrenSum"
                    children:
                    -   class: "UIControl"
                        name: "CaptionRegular"
                        input: false
                        classes: "t-body regular color=white-wild-sand-50-text"
                        components:
                            UITextComponent:
                                multiline: "MULTILINE_ENABLED"
                                align: ["LEFT", "VCENTER"]
                                useRtlAlign: "USE_BY_SYSTEM"
                            Anchor:
                                leftAnchorEnabled: true
                            SizePolicy:
                                horizontalPolicy: "Formula"
                                horizontalFormula: "content + 8"
                                verticalPolicy: "PercentOfContent"
                            StyleSheet:
                                styles: "~res:/UI/Screens3/Font.style.yaml"
                        bindings:
                        - ["UITextComponent.text", "localize(\"ApppearancePanel/CostOfUse\")"]
                    -   class: "UIControl"
                        name: "FreeLabel"
                        input: false
                        classes: "t-subtitle regular color=white-wild-sand-100-text"
                        components:
                            UITextComponent:
                                align: ["LEFT", "VCENTER"]
                            Anchor:
                                leftAnchorEnabled: true
                            SizePolicy:
                                horizontalPolicy: "Formula"
                                horizontalFormula: "content + 8"
                                verticalPolicy: "PercentOfContent"
                            StyleSheet:
                                styles: "~res:/UI/Screens3/Font.style.yaml"
                        bindings:
                        - ["visible", "supplyPrice.resources.Empty()"]
                        - ["UITextComponent.text", "localize(\"ApppearancePanel/CostOfUse/Free\")"]
                    -   prototype: "Currencies/Resources"
                        name: "Resources"
                        components:
                            Anchor:
                                leftAnchorEnabled: true
                            UIDataParamsComponent:
                                args:
                                    "price": "supplyPrice"
