Header:
    version: 133
ImportedPackages:
- "~res:/UI/Screens3/Lobby/Inventory/Camouflages/CamouflagesList.yaml"
- "~res:/UI/Screens3/Lobby/Common/Button.yaml"
- "~res:/UI/Screens3/Lobby/Common/IconButton.yaml"
- "~res:/UI/Screens3/Lobby/Inventory/Camouflages/CamouflageInfo.yaml"
- "~res:/UI/Screens3/Lobby/Inventory/Common/DynamicHorizontalPadding.yaml"
Prototypes:
-   class: "UIControl"
    name: "Screen"
    size: [960.000000, 640.000000]
    input: false
    components:
        UIAnimationComponent:
            animations: "ON_FULLSCREEN_CHANGED,~res:/UI/Screens3/Lobby/Inventory/Camouflages/CamouflagesFullscreen.animation"
        LinearLayout:
            orientation: "TopDown"
        SizePolicy:
            horizontalPolicy: "PercentOfParent"
            verticalPolicy: "PercentOfParent"
        UIDataParamsComponent:
            params:
            - ["bool", "fullscreenMode", "false", "false"]
            - ["ArtefactProviderModel", "artefacts", "null", "{ }"]
            - ["StatsDataModel", "stats", "null", "{ }"]
            - ["bool", "autoresupply", "false", "false"]
            - ["CamouflageSlotInfo", "camouflages", "null", "{ }"]
            events:
            - "CAMOUFLAGES_SIZE_CHANGED"
            - "ON_FULLSCREEN_CHANGED"
            - "ON_CAMO_CLICKED"
            - "ON_FULLSCREEN_CLICKED"
            - "ON_CLICK_ACTION"
            - "ON_AUTORESUPPLY_CHANGED(bool isResupplyOn)"
        UIDataLocalBindingsComponent:
            data:
            - ["Price", "emptyPrice", "{ }"]
            - ["eCamoInShopState", "currentCamoState", "when isNull(camouflages.selectedCamo) -> eCamoInShopState.BUY_DISABLED, camouflages.selectedCamo.state"]
            - ["bool", "hasCertificate", "currentCamoState == eCamoInShopState.UNLOCK_ITEM"]
            - ["Price", "pricePay", "when isNull(camouflages.selectedCamo) -> emptyPrice, currentCamoState == eCamoInShopState.UNLOCK_BUY -> camouflages.selectedCamo.unlockPrice, currentCamoState == eCamoInShopState.UNLOCK_ITEM -> camouflages.selectedCamo.unlockItem, currentCamoState == eCamoInShopState.INSTALL -> camouflages.selectedCamo.supplyPrice, currentCamoState == eCamoInShopState.REPLACE -> camouflages.selectedCamo.supplyPrice, emptyPrice"]
            - ["Price", "priceGet", "when isNull(camouflages.selectedCamo) -> emptyPrice, currentCamoState == eCamoInShopState.RETURN -> camouflages.selectedCamo.supplyPrice, currentCamoState == eCamoInShopState.UNINSTALL -> camouflages.selectedCamo.supplyPrice, currentCamoState == eCamoInShopState.REPLACE and not isNull(camouflages.currentCamo) -> camouflages.currentCamo.supplyPrice, emptyPrice"]
        UIDataLocalControlComponent0:
            name: "footerContent"
            prototypePath: "~res:/UI/Screens3/Lobby/Inventory/Camouflages/CamouflagesPriceFooter.yaml"
            args:
                "artefacts": "artefacts"
                "stats": "stats"
                "autoressuplyVisible": "not (camouflages.slot == eCamouflageKind.CUSTOM_SET)"
                "priceGet": "priceGet"
                "pricePay": "pricePay"
                "state": "currentCamoState"
                "autoResupply": "autoresupply"
            eventActions:
            - ["ON_CLICK_ACTION", "ON_CLICK_ACTION", ""]
            - ["ON_AUTO_RESUPPLY_CHANGED", "ON_AUTO_RESUPPLY_CHANGED", "_event.isResupplyOn"]
        UIEventOnDataComponent0:
            watchedDataExpression: "fullscreenMode"
            eventName: "ON_FULLSCREEN_CHANGED"
            eventData: "fullscreenMode"
    children:
    -   class: "UIControl"
        name: "Panels"
        position: [0.000000, 0.000000]
        input: false
        components:
            Anchor:
                topAnchorEnabled: true
                topAnchor: 50.000000
            LinearLayout: {}
            SizePolicy:
                horizontalPolicy: "PercentOfParent"
                verticalPolicy: "PercentOfParent"
        children:
        -   class: "UIControl"
            name: "KindGroup"
            input: false
            components:
                UIOpacityComponent: {}
                SizePolicy:
                    horizontalPolicy: "FixedSize"
                    horizontalValue: 288.000000
                    verticalPolicy: "PercentOfParent"
                UIChildComponent0:
                    childType: "kOldExpression"
                    control: "when camouflages.group.camoGroups.Empty() -> \"\", \"~res:/UI/Screens3/Lobby/Inventory/Camouflages/CamouflagesList.yaml\""
                    args:
                        "selectedItem": "when isNull(camouflages.selectedCamo) -> -1, camouflages.selectedCamo.itemId"
                        "currentItem": "when isNull(camouflages.currentCamo) -> -1, camouflages.currentCamo.itemId"
                        "slotGroup": "camouflages.group"
                    eventActions:
                    - ["ON_CAMO_CLICKED", "ON_CAMO_CLICKED", "_event"]
                UIIdentifierComponent:
                    id: "camos_container"
        -   class: "UIControl"
            name: "Content"
            input: false
            components:
                LinearLayout:
                    orientation: "TopDown"
                    spacing: 16.000000
                SizePolicy:
                    horizontalPolicy: "PercentOfParent"
                    verticalPolicy: "PercentOfParent"
                UILayoutEventComponent:
                    sizeChangedEvent: "CAMOUFLAGES_SIZE_CHANGED"
                    sizeChangedEventData: "_absoluteRect"
            children:
            -   class: "UIControl"
                name: "header"
                size: [643.000000, 48.000000]
                input: false
                components:
                    LinearLayout:
                        orientation: "RightToLeft"
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                    Sound:
                        touchUpInside: "hits/tank_death/tank_death"
                children:
                -   prototype: "DynamicHorizontalPadding/DynamicHorizontalPadding"
                    name: "DynamicHorizontalPadding"
                    classes: "padding only-notch-padding"
                -   prototype: "IconButton/IconButton"
                    name: "FullscreenButton"
                    components:
                        Anchor:
                            topAnchorEnabled: true
                            topAnchor: 16.000000
                        UIDataParamsComponent:
                            args:
                                "visible": "true"
                                "image": "\"~res:/Gfx/Lobby/icons/icon_eye_s\""
                                "type": "eButtonType.OPTIONAL_DARK"
                                "sound": "eButtonSound.CHOOSE"
                                "enabled": "true"
                            eventActions:
                            - ["ON_CLICK_BUTTON", "ON_FULLSCREEN_CLICKED", ""]
                        Sound:
                            touchUpInside: "hits/tank_death/tank_death"
            -   class: "UIControl"
                name: "Content"
                position: [0.000000, 64.000000]
                size: [32.000000, 32.000000]
                visible: true
                input: false
                components:
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfParent"
            -   class: "UIControl"
                name: "InfoWrapper"
                input: false
                components:
                    UIOpacityComponent: {}
                    Anchor:
                        rightAnchorEnabled: true
                    LinearLayout:
                        orientation: "RightToLeft"
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfLastChild"
                children:
                -   prototype: "DynamicHorizontalPadding/DynamicHorizontalPadding"
                    name: "DynamicHorizontalPadding"
                    classes: "padding only-notch-padding"
                -   class: "UIControl"
                    name: "InfoContainer"
                    size: [32.000000, 32.000000]
                    input: false
                    components:
                        Anchor:
                            rightAnchorEnabled: true
                        LinearLayout:
                            orientation: "TopDown"
                            spacing: 16.000000
                        SizePolicy:
                            horizontalPolicy: "PercentOfParent"
                            verticalPolicy: "PercentOfChildrenSum"
                    children:
                    -   class: "UIControl"
                        name: "BodyKit"
                        size: [32.000000, 32.000000]
                        input: false
                        components:
                            Anchor:
                                rightAnchorEnabled: true
                            SizePolicy:
                                horizontalPolicy: "FixedSize"
                                horizontalValue: 86.000000
                                verticalPolicy: "FixedSize"
                                verticalValue: 104.000000
                        bindings:
                        - ["visible", "hasCertificate"]
                        children:
                        -   class: "UIControl"
                            name: "Background"
                            size: [32.000000, 32.000000]
                            input: false
                            components:
                                Background:
                                    drawType: "DRAW_STRETCH_BOTH"
                                    sprite: "~res:/Gfx/Lobby/backgrounds/bg_item-dark_r4"
                                    leftRightStretchCap: 4.000000
                                    topBottomStretchCap: 4.000000
                                UIRoundedCornersComponent:
                                    radius: "4"
                                SizePolicy:
                                    horizontalPolicy: "PercentOfParent"
                                    verticalPolicy: "PercentOfParent"
                        -   class: "UIControl"
                            name: "BodyKitHolder"
                            size: [86.000000, 104.000000]
                            input: false
                            components:
                                SizePolicy:
                                    horizontalPolicy: "PercentOfParent"
                                    verticalPolicy: "PercentOfParent"
                                UIChildComponent0:
                                    condition: "hasCertificate and not isNull(pricePay) and not (Empty(pricePay.resources))"
                                    prototypePath: "~res:/UI/Screens3/Lobby/Common/Resource/Detailed/StuffMedium.yaml"
                                    args:
                                        "fx": "null"
                                        "stuff": "{ \"name\" = pricePay.resources[0].name; \"iconUrl\" = pricePay.resources[0].iconUrl; \"icon\" = pricePay.resources[0].icon; \"grade\" = pricePay.resources[0].grade; \"quantity\" = pricePay.resources[0].quantity; }"
                    -   prototype: "CamouflageInfo/Info"
                        name: "Info"
                        components:
                            Anchor:
                                rightAnchorEnabled: true
                            UIDataParamsComponent:
                                args:
                                    "slot": "camouflages.slot"
                                    "state": "when isNull(camouflages.selectedCamo) -> eCamoInShopState.HIDDEN, camouflages.selectedCamo.state"
                                    "camouflageLock": "when isNull(camouflages.selectedCamo) -> null, camouflages.selectedCamo.lockInfo"
                                    "supplyPrice": "when isNull(camouflages.selectedCamo) -> emptyPrice, camouflages.selectedCamo.supplyPrice"
                                    "description": "when isNull(camouflages.selectedCamo) -> \"\", camouflages.selectedCamo.description"
                                    "visible": "not isNull(camouflages.selectedCamo)"
                                    "name": "when isNull(camouflages.selectedCamo) -> \"\", camouflages.selectedCamo.name"
            -   class: "UIControl"
                name: "FooterWrapper"
                input: false
                components:
                    UIOpacityComponent: {}
                    SizePolicy:
                        horizontalPolicy: "PercentOfParent"
                        verticalPolicy: "PercentOfFirstChild"
                bindings:
                - ["visible", "not isNull(camouflages.selectedCamo)"]
                children:
                -   class: "UIControl"
                    name: "Footer"
                    input: false
                    components:
                        Anchor:
                            bottomAnchorEnabled: true
                        SizePolicy:
                            horizontalPolicy: "PercentOfParent"
                            verticalPolicy: "PercentOfFirstChild"
                        UIChildComponent0:
                            prototypePath: "~res:/UI/Screens3/Common/Footer.yaml"
                            args:
                                "content": "when not isNull(camouflages.selectedCamo) -> footerContent, null"
                                "bgStyle": "\"grey-shark-70-bg\""
                                "desktopStyle": "\"\""
