Header:
    version: "92"
ImportedPackages:
- "~res:/UI/Screens3/Common/Touch.style.yaml"
- "~res:/UI/Screens3/Common/Hover.style.yaml"
StyleSheets:
-   selectors:
    - ".optional-device:selected:hover * .hover"
    - ".optional-device:pressed_inside * .hover"
    - ".optional-device:selected * .hover"
    - ".optional-device:pressed_inside:hover * .hover"
    properties:
        visible: false
-   selectors:
    - ".optional-device * .content-area"
    - ".optional-device:pressed_inside:selected * .content-area"
    properties:
        opacity-opacity:
            value: 1.000000
            transitionTime: 0.080000
            transitionFunction: "EASE_IN_EASY_OUT"
-   selectors:
    - ".optional-device:pressed_inside * .content-area"
    properties:
        opacity-opacity:
            value: 0.700000
            transitionTime: 0.080000
            transitionFunction: "EASE_IN_EASY_OUT"
